# Generated by Django 5.2.17 on 2026-08-20 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='Government Polytechnic Bansdeeh, Ballia', max_length=255)),
                ('bteup_code', models.CharField(default='4412', max_length=50)),
                ('aicte_approval', models.CharField(default='Approved by AICTE, New Delhi', max_length=150)),
                ('history', models.TextField(default='Government Polytechnic Bansdeeh, Ballia was established by the Government of Uttar Pradesh to impart quality technical education and foster industrial competencies in rural and semi-urban youth of Purvanchal.')),
                ('vision', models.TextField(default='To be a premier technical institute in Uttar Pradesh fostering innovative diploma engineers with sound technical skills, professional ethics, and societal dedication.')),
                ('mission', models.TextField(default='Provide state-of-the-art laboratory infrastructure, industry-aligned diploma training, and holistic personal development for aspiring diploma technicians.')),
                ('principal_name', models.CharField(default='Er. R. C. Srivastava', max_length=150)),
                ('principal_message', models.TextField(default='Welcome to Government Polytechnic Bansdeeh, Ballia. Our institution is dedicated to building robust technical foundation, practical engineering skills, and career opportunities for our diploma students under BTEUP curriculum.')),
                ('principal_photo', models.URLField(default='https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=faces', max_length=500)),
                ('achievements', models.JSONField(blank=True, default=list)),
                ('key_highlights', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About College Information',
                'verbose_name_plural': 'About College Information',
            },
        ),
        migrations.CreateModel(
            name='CollegeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Near Bansdeeh Road Railway Station, Bansdeeh, Ballia, Uttar Pradesh - 277202', max_length=300)),
                ('district', models.CharField(default='Ballia', max_length=100)),
                ('state', models.CharField(default='Uttar Pradesh', max_length=100)),
                ('pincode', models.CharField(default='277202', max_length=20)),
                ('landmark', models.CharField(default='Near Bansdeeh Road, State Highway 1', max_length=200)),
                ('latitude', models.FloatField(default=25.8647)),
                ('longitude', models.FloatField(default=84.2185)),
                ('map_embed_url', models.URLField(default='https://maps.google.com/maps?q=Bansdeeh,Ballia,Uttar+Pradesh&t=&z=14&ie=UTF8&iwloc=&output=embed', max_length=1000)),
                ('map_view_url', models.URLField(default='https://maps.google.com/?q=25.8647,84.2185', max_length=1000)),
                ('directions_url', models.URLField(default='https://www.google.com/maps/dir//Bansdeeh+Ballia+Uttar+Pradesh+277202', max_length=1000)),
                ('connectivity_bus', models.CharField(default='Regular UPSRTC and local buses from Ballia City Bus Stand (18 km) and Bansdeeh Market (3 km).', max_length=300)),
                ('connectivity_train', models.CharField(default='Nearest Railway Stations: Bansdeeh Road (BUI) - 4 km, Ballia Junction (BUI) - 19 km.', max_length=300)),
                ('contact_phone', models.CharField(default='+91 94150 24510', max_length=50)),
                ('contact_email', models.EmailField(default='principal.gpbansdeeh@gmail.com', max_length=254)),
            ],
            options={
                'verbose_name': 'College Location & Coordinates',
                'verbose_name_plural': 'College Location & Coordinates',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Laboratories', 'Laboratories'), ('Smart Classroom', 'Smart Classroom'), ('Library', 'Central Library'), ('Workshops', 'Workshops'), ('Computer Labs', 'Computer Labs'), ('Sports', 'Sports & Gymnasium'), ('Campus', 'Campus Infrastructure'), ('Hostel', 'Hostel & Mess'), ('Other', 'Other Facilities')], default='Laboratories', max_length=50)),
                ('cover_image', models.URLField(blank=True, max_length=500)),
                ('short_description', models.CharField(max_length=300)),
                ('detailed_notes', models.TextField(blank=True)),
                ('equipment_list', models.JSONField(blank=True, default=list)),
                ('display_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Published', max_length=20)),
                ('created_by', models.CharField(default='Administration', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campus Facility',
                'verbose_name_plural': 'Campus Facilities',
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(max_length=500)),
                ('category', models.CharField(choices=[('Campus', 'Campus'), ('Classrooms', 'Classrooms'), ('Laboratories', 'Laboratories'), ('Workshops', 'Workshops'), ('Events', 'Events'), ('Sports', 'Sports'), ('Library', 'Library'), ('Cultural Activities', 'Cultural Activities'), ('Other', 'Other')], default='Campus', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('uploaded_by', models.CharField(default='College Media Cell', max_length=150)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImportantLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('category', models.CharField(choices=[('Technical Education', 'Technical Education'), ('Examination & Board', 'Examination & Board'), ('Scholarship & Welfare', 'Scholarship & Welfare'), ('Admission & Entrance', 'Admission & Entrance'), ('Digital Learning', 'Digital Learning'), ('Official Resources', 'Official Resources')], default='Official Resources', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PublicFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='All Engineering Diploma Branches', max_length=150)),
                ('academic_year', models.CharField(default='2025-2026', max_length=50)),
                ('fee_type', models.CharField(default='Tuition & Registration Fee', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=12450.0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='Subject to UP State Government & BTEUP guidelines.')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Public Fee Structure',
                'verbose_name_plural': 'Public Fee Structures',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FacilityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.facility')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
