# Generated by Django 5.2.17 on 2026-08-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('enrollment_number', models.CharField(blank=True, max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('mobile', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('branch', models.CharField(max_length=150)),
                ('semester', models.IntegerField(default=1)),
                ('admission_year', models.IntegerField(default=2023)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], default='General', max_length=20)),
                ('blood_group', models.CharField(blank=True, default='B+', max_length=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Alumni', 'Alumni')], default='Active', max_length=20)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('attendance_percentage', models.FloatField(default=85.0)),
                ('fee_status', models.CharField(choices=[('Paid', 'Paid'), ('Partial', 'Partial'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
