# Generated by Django 5.2.17 on 2026-08-20 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Personal Information Correction', 'Personal Information Correction'), ('Name Correction Request', 'Name Correction Request'), ('Attendance Issue', 'Attendance Issue'), ('Fee / Payment Issue', 'Fee / Payment Issue'), ('Examination & Result Issue', 'Examination & Result Issue'), ('Document / Certificate Request', 'Document / Certificate Request'), ('Hostel / Mess Request', 'Hostel / Mess Request'), ('Other Grievance / Problem', 'Other Grievance / Problem')], default='Personal Information Correction', max_length=100)),
                ('description', models.TextField()),
                ('attachment_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Resolved', 'Resolved')], default='Submitted', max_length=30)),
                ('staff_response', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Application / Grievance',
                'verbose_name_plural': 'Student Applications & Grievances',
                'ordering': ['-created_at'],
            },
        ),
    ]
