# Generated by Django 5.2.17 on 2026-08-22 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('request_type', models.CharField(choices=[('NEW_STUDENT', 'New Student Registration'), ('FEE_UPDATE', 'Fee Payment / Status Update'), ('STUDENT_UPDATE', 'Student Information Update'), ('ATTENDANCE_UPDATE', 'Attendance Adjustment')], default='FEE_UPDATE', max_length=50)),
                ('submitted_by_name', models.CharField(default='Faculty Member', max_length=150)),
                ('submitted_by_email', models.CharField(blank=True, max_length=150)),
                ('student_name', models.CharField(max_length=150)),
                ('roll_number', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(blank=True, max_length=150)),
                ('semester', models.IntegerField(default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Admin Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('admin_remarks', models.TextField(blank=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='students.student')),
            ],
            options={
                'verbose_name': 'Staff Approval Request',
                'verbose_name_plural': 'Staff Approval Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
