# Generated by Django 5.2.17 on 2026-08-22 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_staffapprovalrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student & Staff Application', 'verbose_name_plural': 'Student & Staff Applications'},
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='recipient_email',
            field=models.CharField(default='principal.gpbansdeeh@gmail.com', max_length=150),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='recipient_name',
            field=models.CharField(default='Er. R. C. Srivastava (Principal)', max_length=150),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='recipient_role',
            field=models.CharField(default='principal', max_length=50),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='sender_email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='sender_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='sender_role',
            field=models.CharField(default='student', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.student'),
        ),
    ]
