# Generated by Django 5.2.17 on 2026-08-19 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=150)),
                ('semester', models.IntegerField(default=1)),
                ('subject', models.CharField(max_length=150)),
                ('subject_code', models.CharField(max_length=50)),
                ('exam_date', models.DateField()),
                ('start_time', models.CharField(default='09:30 AM', max_length=20)),
                ('end_time', models.CharField(default='12:30 PM', max_length=20)),
                ('room_no', models.CharField(default='Hall A-102', max_length=50)),
                ('max_marks', models.IntegerField(default=50)),
                ('passing_marks', models.IntegerField(default=17)),
                ('exam_type', models.CharField(default='Theory', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=150)),
                ('semester', models.IntegerField(default=4)),
                ('academic_year', models.CharField(default='2025-2026', max_length=50)),
                ('grand_total_max', models.IntegerField(default=700)),
                ('grand_total_obtained', models.IntegerField(default=585)),
                ('percentage', models.FloatField(default=83.57)),
                ('cgpa', models.FloatField(default=8.5)),
                ('division', models.CharField(default='First Division with Honours', max_length=50)),
                ('status', models.CharField(default='PASSED', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=150)),
                ('theory_max', models.IntegerField(default=50)),
                ('theory_obtained', models.IntegerField(default=42)),
                ('practical_max', models.IntegerField(default=50)),
                ('practical_obtained', models.IntegerField(default=45)),
                ('total_max', models.IntegerField(default=100)),
                ('total_obtained', models.IntegerField(default=87)),
                ('grade', models.CharField(default='A+', max_length=10)),
                ('status', models.CharField(default='PASS', max_length=20)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='examinations.studentresult')),
            ],
        ),
    ]
