# Generated by Django 5.2.17 on 2026-08-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('emp_code', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('department', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('mobile', models.CharField(max_length=25)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('experience_years', models.IntegerField(default=5)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
