# Generated by Django 5.2.17 on 2026-08-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(default='Government Polytechnic Campus Staff Quarters, Bansdeeh, Ballia (U.P.) - 277202'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(blank=True, default=38, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='blood_group',
            field=models.CharField(default='B+', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pay_scale',
            field=models.CharField(default='7th CPC Level 10 (₹56,100 - ₹1,77,500)', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='promotion_status',
            field=models.CharField(default='Regular Confirmed • Eligible for Next CAS Review', max_length=255),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=78500.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='teacher',
            name='staff_type',
            field=models.CharField(default='Teaching Faculty', max_length=50),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_description',
            field=models.TextField(blank=True, default='Conducts theory lectures & lab practical sessions, manages departmental laboratory.'),
        ),
    ]
