# Generated by Django 5.2.17 on 2026-08-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Examination', 'Examination'), ('Fees', 'Fees'), ('Events', 'Events'), ('Academic', 'Academic'), ('Holiday', 'Holiday'), ('General', 'General')], default='General', max_length=50)),
                ('publish_date', models.DateField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('target_audience', models.CharField(choices=[('All', 'All'), ('Students', 'Students'), ('Teachers', 'Teachers')], default='All', max_length=20)),
                ('issued_by', models.CharField(default='Office of the Principal', max_length=150)),
                ('reference_no', models.CharField(default='GPB/ADMIN/2026/101', max_length=100)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_date', '-id'],
            },
        ),
    ]
