# Generated by Django 5.2.17 on 2026-08-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeitem',
            name='discussion_comments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noticeitem',
            name='is_confidential_staff',
            field=models.BooleanField(default=False),
        ),
    ]
