# Generated by Django 5.2.17 on 2026-08-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=150)),
                ('semester', models.IntegerField(default=1)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('subject_code', models.CharField(blank=True, max_length=50)),
                ('teacher_name', models.CharField(max_length=150)),
                ('room_no', models.CharField(max_length=50)),
                ('slot_type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical'), ('Tutorial', 'Tutorial')], default='Theory', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
