# Generated by Django 5.2.17 on 2026-08-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('course_name', models.CharField(max_length=150)),
                ('short_code', models.CharField(max_length=50)),
                ('duration_years', models.IntegerField(default=3)),
                ('total_seats', models.IntegerField(default=60)),
                ('active_students', models.IntegerField(default=55)),
                ('faculty_count', models.IntegerField(default=6)),
                ('hod_name', models.CharField(blank=True, max_length=150)),
                ('labs_count', models.IntegerField(default=4)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
