# Generated by Django 5.2.17 on 2026-08-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='Government Polytechnic Bansdeeh, Ballia', max_length=255)),
                ('hindi_name', models.CharField(default='राजकीय पॉलिटेक्निक बांसडीह, बलिया', max_length=255)),
                ('address', models.TextField(default='Bansdeeh, Ballia, Uttar Pradesh - 277202')),
                ('phone', models.CharField(default='+91 5498 290124', max_length=50)),
                ('email', models.EmailField(default='principal.gpbansdeeh@gmail.com', max_length=254)),
                ('website', models.CharField(default='https://gpbansdeeh.ac.in', max_length=255)),
                ('aicte_code', models.CharField(default='1-3328491021', max_length=50)),
                ('bteup_code', models.CharField(default='4412', max_length=50)),
                ('principal_name', models.CharField(default='Er. R. C. Srivastava', max_length=150)),
                ('custom_logo_url', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
    ]
